### PR TITLE
added: Python PKGBUILD generation script.

### PR DESCRIPTION
**Pull request by kvij**
I noticed that updates happen quite often so I wanted to help out by creating a PKGBUILD generator. It creates a PKGBUILD file from the PKGBUILD.j2 template with the latest version info and correct checksums (unless the download went wrong).

I do have some reservations on where to put it. Right now the repository contains only what is absolutely necessary; my additions spoil that. Perhaps a subdir is good enough but perhaps a separate repository is best.
I am willing to put in some extra work to checksum and insert the other source files and update the .SRCINFO file.

### CODE REVIEW

**Comment by RPDiep** [comment]
Good thinking.
I think a separate directory as you suggested would be cleanest.
I have no idea what it would mean for pacaur for example if the existing
contents would be put in another directory and the script and ninja
template in another directory next to it. So just a directory named
generator and perhaps some comment about it in a readme seems a great thing
to have.

Op 25 jun. 2017 22:35 schreef "kvij" <notifications@github.com>:

**Comment by kvij** [comment]
@RPDiep I think I have done what you wanted. As there is no toplevel readme I have added one in the generator directory. I think documenting it was a brilliant idea however by placing it in a subdir there is no improvement in visibility.

**Comment by RPDiep** [comment]
Nice, thanks. I will check if the script works with python2 as well (although I would like to see it gone someday 🙂)
I might add a `requirements.txt` for pip, too.

**Comment by kvij** [comment]
Thanks for the quick merger. Hope you don't have to get up early  :worried:
Please feel free to make any changes you see fit or point out any major issues. This is the third time I have used python for something (didn't even know about the requirements.txt).

**Pull request merged**
